# generated by ~/michael.trigoboff/bin/creat_makefile.py

# C++ compiler flags
include ~michael.trigoboff/bin/makeflags_g++

asgmt04:	bst.o gcs.o bst.h

bst.o:		bst.h

gcs.o:		gcs.h

.PHONY: x
x:			# clean the directory
			rm -f *.o asgmt04
